// Code generated by ent, DO NOT EDIT.

//go:build tools
// +build tools

// Package internal holds a loadable version of the latest schema.
package internal

const Schema = `{"Schema":"entdemo/ent/schema","Package":"entdemo/ent","Schemas":[{"name":"User","config":{"Table":""},"fields":[{"name":"age","type":{"Type":12,"Ident":"","PkgPath":"","PkgName":"","Nillable":false,"RType":null},"validators":1,"position":{"Index":0,"MixedIn":false,"MixinIndex":0}},{"name":"name","type":{"Type":7,"Ident":"","PkgPath":"","PkgName":"","Nillable":false,"RType":null},"default":true,"default_value":"unknown","default_kind":24,"position":{"Index":1,"MixedIn":false,"MixinIndex":0}}]}],"Features":["sql/execquery","schema/snapshot"]}`
